name: Deploy Next.js to GitHub Pages

permissions:
  id-token: write
  contents: read
  pages: write
  deployments: write

concurrency: 
  group: "pages-deploy"
  cancel-in-progress: true

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      deployment_id: ${{ steps.deployment.outputs.deployment_id }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Configure Pages
        uses: actions/configure-pages@v4  # Ключевое добавление!

      - name: Create Deployment
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          target-dir: './docs'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          deployment_id: ${{ needs.build.outputs.deployment_id }}