


name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # Используем кастомный токен вместо системного
          github_token: ${{ secrets.GH_DEPLOY_TOKEN }}
          publish_dir: ./docs
          # Указываем явно репозиторий
          repository_name: zangrieax/site-ads
          # Очищаем историю коммитов
          force_orphan: true
          # Создаем пустой коммит если нужно
          allow_empty_commit: true