


name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
      - name: Ensure .nojekyll exists
        run: |
          if [ ! -f "docs/.nojekyll" ]; then
            echo "⚠️ .nojekyll missing! Creating..."
            touch docs/.nojekyll
          fi
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: docs/
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    needs: build
    steps:
      - name: Verify token
        run: |
          echo "Token length: ${#GH_DEPLOY_TOKEN}"
          if [ -z "$GH_DEPLOY_TOKEN" ]; then 
            echo "ERROR: Token is empty!"; 
            exit 1;
          else
            echo "Token exists";
          fi
        env:
          GH_DEPLOY_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # Используем кастомный токен вместо системного
          github_token: ${{ secrets.GH_DEPLOY_TOKEN }}
          publish_dir: ./docs
          # Указываем явно репозиторий
          repository_name: zangrieax/site-ads
          # Очищаем историю коммитов
          force_orphan: true
          # Создаем пустой коммит если нужно
          allow_empty_commit: true